### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by tamma12** [Newmcpe/fuflohamster#1]
please add tutorial to run

**Comment by Newmcpe** [comment]
hi! there is tutorial in readme.md

**Comment by tamma12** [comment]
> hi! there is tutorial in readme.md

Tutorial how make refferal

**Comment by Newmcpe** [comment]
Paste your authkeys to [availableaccounts.txt](https://github.com/Newmcpe/fuflohamster/blob/master/availableaccounts.txt)

**Comment by tamma12** [comment]
> Paste your authkeys to [availableaccounts.txt](https://github.com/Newmcpe/fuflohamster/blob/master/availableaccounts.txt)
