### ISSUE TITLE
how add referal

### ISSUE THREAD

**Issue by tamma12** [Newmcpe/fuflohamster#2]
![Screenshot_332](https://github.com/Newmcpe/fuflohamster/assets/13850026/895dc37e-5d4f-47c0-90a6-3e825a1ff7f3)
how  Добавить аккаунты для накрутки рефералов (загрузите в availableaccounts.txt)

**Comment by Newmcpe** [comment]
Paste your authkeys to [availableaccounts.txt](https://github.com/Newmcpe/fuflohamster/blob/master/availableaccounts.txt)

**Comment by tamma12** [comment]
Can you give an example of how to get the authkey?

**Comment by tamma12** [comment]
> Paste your authkeys to [availableaccounts.txt](https://github.com/Newmcpe/fuflohamster/blob/master/availableaccounts.txt)

Can you give an example of how to get the authkey?

**Comment by Newmcpe** [comment]
![image](https://github.com/Newmcpe/fuflohamster/assets/17596135/43b50f08-8f05-4c46-94ff-665f0e3a9fa1)
It is usually given in the services where you buy telegram accounts. lzt.market for example:
